name: billboard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1

  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  firebase_storage: ^11.1.1
  firebase_auth: ^4.4.2
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1

  jwt_decoder: ^2.0.1
  lottie: ^2.6.0
  image_picker: ^1.0.4
  pinput: ^3.0.1
  intl: ^0.18.1
  flutter_custom_clippers: ^2.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.0
  outline_search_bar: ^2.3.0
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.5.3
  syncfusion_flutter_charts: 21.2.6
  permission_handler: ^11.3.0
  flutter_masked_text2: ^0.9.1
  url_launcher: ^6.2.2
  fancy_password_field: ^2.0.2
  animated_rating_stars: ^1.0.1
  flutter_stripe: ^10.1.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/